// P-OPEN-SOURCE-SPLIT — public BYOK credential generator (build-time codegen,
// NOT an agent tool; no child_process). The public build twin of
// scripts/gen-default-credentials.ts: it ALWAYS writes null defaults and
// ignores the historical FRONDOSE_DEFAULT_* embedding env vars, so no key
// material can ever enter a public build artifact. The compiled App reads
// provider keys exclusively from the operator's own auth/secrets store.
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = process.cwd();
const OUT_DIR = "src/persistence";
const OUT_FILENAME = "defaultCredentials.generated.json";

const payload = {
  _generated: "GENERATED by scripts/gen-public-default-credentials.ts — public BYOK build; DO NOT COMMIT.",
  llmBaseUrl: null,
  llmModel: null,
  llmKey: null,
};

function main(): void {
  const outDir = resolve(ROOT, OUT_DIR);
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
  writeFileSync(resolve(outDir, OUT_FILENAME), `${JSON.stringify(payload, null, 2)}\n`, "utf-8");
  // tsc does not copy .json into dist/: dual-write so the packaged runtime
  // carries the (all-null, BYOK) credentials skeleton the policy checks for.
  // Unconditional — the generator runs BEFORE tsc on a fresh checkout where
  // dist/ does not exist yet (an existsSync gate silently skipped the write
  // on CI and the packaged runtime shipped without the member).
  const distDir = resolve(ROOT, "dist", OUT_DIR.replace(/^src\//, ""));
  mkdirSync(distDir, { recursive: true });
  writeFileSync(resolve(distDir, OUT_FILENAME), `${JSON.stringify(payload, null, 2)}\n`, "utf-8");
}

main();
