// P-Y2.2a — build-time codegen (NOT an agent tool; no child_process; runs in `npm run build`
// before tsc, like build:web's esbuild/tailwind step). Emits two committed generated modules:
//   src/overlay/sharedRenderBundle.generated.ts  — the shared builders as an IIFE string
//   src/overlay/frondoseCss.generated.ts         — index.html's <style>, shadow-scoped
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { build, type Plugin } from "esbuild";
import { OVERLAY_LAYOUT_OVERRIDES, OVERLAY_TAKEOVER_CSS, transformCssForShadow } from "../src/overlay/cssTransform.js";

const ROOT = process.cwd();
const HEADER = "// GENERATED by scripts/gen-overlay-assets.ts — DO NOT EDIT.\n";

// Resolve relative `.js` imports to their `.ts` source so the bundle reflects the CURRENT
// render.ts/mode.ts/frondoseTokens.ts — NOT the committed (possibly stale) sibling .js build
// artifacts (src/tauri/ui/render.js is git-tracked; F-Y5-1 stale-dist class). NodeNext source
// imports carry `.js` extensions; without this esbuild would prefer the literal `.js` file.
const tsSourceResolve: Plugin = {
  name: "ts-source-resolve",
  setup(b) {
    b.onResolve({ filter: /\.js$/ }, (args) => {
      if (args.kind === "entry-point" || !args.path.startsWith(".")) return undefined;
      const tsPath = resolve(args.resolveDir, args.path.replace(/\.js$/, ".ts"));
      return existsSync(tsPath) ? { path: tsPath } : undefined;
    });
  },
};

async function genBundle(): Promise<void> {
  const result = await build({
    entryPoints: [resolve(ROOT, "src/overlay/sharedEntry.ts")],
    bundle: true,
    format: "iife",
    globalName: "__frondoseShared",
    platform: "browser",
    target: "es2022",
    write: false,
    plugins: [tsSourceResolve],
  });
  const iife = result.outputFiles[0]?.text ?? "";
  if (!iife.includes("__frondoseShared")) throw new Error("gen-overlay-assets: empty/invalid bundle");
  // JSON.stringify → a safe double-quoted JS string literal regardless of backticks/${} in render.ts.
  writeFileSync(
    resolve(ROOT, "src/overlay/sharedRenderBundle.generated.ts"),
    `${HEADER}export const SHARED_RENDER_JS = ${JSON.stringify(iife)};\n`,
  );
}

function genCss(): void {
  const html = readFileSync(resolve(ROOT, "src/tauri/ui/index.html"), "utf8");
  const m = html.match(/<style>([\s\S]*?)<\/style>/);
  if (!m || m[1] === undefined) throw new Error("gen-overlay-assets: <style> not found in index.html");
  const scoped = `${transformCssForShadow(m[1])}\n${OVERLAY_LAYOUT_OVERRIDES}\n${OVERLAY_TAKEOVER_CSS}`;
  writeFileSync(
    resolve(ROOT, "src/overlay/frondoseCss.generated.ts"),
    `${HEADER}export const FRONDOSE_CSS = ${JSON.stringify(scoped)};\n`,
  );
}

await genBundle();
genCss();
console.log("[gen-overlay-assets] wrote sharedRenderBundle.generated.ts + frondoseCss.generated.ts");
