// P-EMBED-KEYS build-time codegen (NOT an agent tool; no child_process; runs in
// `npm run build` / `build:tauri` — mirrors scripts/gen-overlay-assets.ts). Reads
// FRONDOSE_DEFAULT_LLM_BASEURL / FRONDOSE_DEFAULT_LLM_MODEL / FRONDOSE_DEFAULT_LLM_KEY
// and writes a JSON sidecar that src/persistence/defaultCredentials.ts
// reads at runtime — co-located under BOTH src/persistence/ (dev/tests running via tsx)
// and dist/persistence/ (the compiled sidecar copied wholesale into the .app by
// build-release.sh's `cp -R dist`). The generated file is gitignored and holds real
// key material ONLY when the operator sets these env vars for a release build; a
// normal dev/CI build with none set writes an all-null file (no behavior change).
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = process.cwd();
const OUT_DIRS = ["src/persistence", "dist/persistence"];
const OUT_FILENAME = "defaultCredentials.generated.json";

function nonEmpty(v: string | undefined): string | null {
  const trimmed = v?.trim();
  return trimmed ? trimmed : null;
}

const payload = {
  _generated: "GENERATED by scripts/gen-default-credentials.ts — DO NOT COMMIT (gitignored).",
  llmBaseUrl: nonEmpty(process.env.FRONDOSE_DEFAULT_LLM_BASEURL),
  llmModel: nonEmpty(process.env.FRONDOSE_DEFAULT_LLM_MODEL),
  llmKey: nonEmpty(process.env.FRONDOSE_DEFAULT_LLM_KEY),
};

function main(): void {
  const json = `${JSON.stringify(payload, null, 2)}\n`;
  for (const dir of OUT_DIRS) {
    const outDir = resolve(ROOT, dir);
    if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
    writeFileSync(resolve(outDir, OUT_FILENAME), json, "utf-8");
  }

  const embedded = [
    payload.llmBaseUrl && "llm.baseUrl",
    payload.llmModel && "llm.model",
    payload.llmKey && "llm.key",
  ].filter((entry): entry is string => Boolean(entry));

  if (payload.llmBaseUrl && !payload.llmKey) {
    process.stderr.write(
      "[gen-default-credentials] WARNING: FRONDOSE_DEFAULT_LLM_BASEURL set without _LLM_KEY — LLM default will NOT be seeded.\n",
    );
  }

  console.log(
    embedded.length > 0
      ? `[gen-default-credentials] wrote ${OUT_FILENAME} with: ${embedded.join(", ")}`
      : `[gen-default-credentials] wrote ${OUT_FILENAME} with NO defaults (env unset) — behaves identically to today`,
  );
}

main();
